name: CI

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: build
      env:
        DOCKER_BUILDKIT: 1
      run: docker build --build-arg testArg=${GITHUB_REF##*/} -t test .
    - name: run
      run: docker run --rm test ls
    - name: echo
      run: echo ${GITHUB_REF##*/}
