name: CI

on: push

jobs:
  build:
    runs-on: self-hosted
    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
    steps:
    - uses: actions/checkout@v2
    - uses: zerosuxx/deployer:latest
    - name: build
      #if: startsWith(github.ref, 'refs/tags')
      run: docker-build --build-arg testArg=${GITHUB_REF##*/} -t test .
    - name: run
      run: docker ps
    - name: Login To DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

