name: CI

on: push

jobs:
  build:
    runs-on: "ubuntu-latest" #self-hosted
    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
    steps:
      - name: test
        run: pwd && df -h .
    #  - name: test
    #    run: id #env && git clone "https://${GITHUB_REPOSITORY_OWNER}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" && ls -al test-actions 
    #- uses: actions/checkout@v2
    #- name: build
    # if: startsWith(github.ref, 'refs/tags')
    #  run: docker build --build-arg testArg=${GITHUB_REF##*/} -t test .
    #- name: run
    #  run: docker ps && curl 12.1.1.1:2376
    #- name: Login To DockerHub Registry
    #  run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

