name: DataFlow

on:
  workflow_dispatch:
    inputs:
      project1:
        description: 'Project1'
        required: false
        type: boolean
  push:
    paths:
      - 'projects/**'

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Project1: $PROJECT1"
        env:
          PROJECT1: ${{ github.event.inputs.project1 }}

  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v17.3

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
