name: Matrix

on: workflow_dispatch

jobs:
  nix_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          set -ex
          nix-shell -p vault
          cp -R $(nix eval -f '<nixpkgs>' --raw vault)/bin /tmp/bin
        env:
          NIXPKGS_ALLOW_UNFREE: 1
      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: /tmp/bin/
          include-hidden-files: true
