name: Matrix

on: workflow_dispatch

jobs:
  nix_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05
      - run: |
          nix-shell -p vault
          nix eval -f '<nixpkgs>' --raw vault
