name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Client Publish
      uses: zerosuxx/zerosuxx-example-github-action@v1
      with:
        target: 'production'
