name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
  
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()    # run this step even if previous step failed
      with:
        name: Results           # Name of the check run which will be created
        path: junit.xml    # Path to test results
        reporter: jest-junit         # Format of test results
        fail-on-error: 'false'

