name: Run Workflow on PR Comment

on:
  issue_comment:
    types:
      - created
  
jobs:
  run:
    if: contains(fromJSON('["/plan","/apply"]'), github.event.comment.body) && github.event.issue.pull_request
    uses: ./.github/workflows/pr-sync.yaml
    with:
      action: ${{ github.event.comment.body }}
