name: CI

on: 
  pull_request:
    types:
      - closed
    branches:
      - 'spike/*-*'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: test
        run: echo '${{ github }}'
