name: PrSync

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: test
        run: echo '${{ toJSON(github) }}'
      - name: modified files
        run: git diff --name-only origin/master
