name: PrSync

on:
  workflow_dispatch:
  pull_request:
    types:
      # - opened
      # - synchronize
      - labeled
  push:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: test
        run: echo "${{ toJSON(github) }}"
