name: PrSync

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: test
        run: echo '${{ toJSON(github) }}'
      - name: modified files
        run: git diff --name-only origin/master

      - uses: jdx/mise-action@v2
        with:
          tool_versions: |
            terraform 1.10.3
            terragrunt 0.71.1

      - run: terragrunt --version
