name: PrSync

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: test
        run: echo '${{ toJSON(github) }}'
      - name: modified files
        run: git diff --name-only origin/master

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: '1.10.3'
          tg_version: '0.71.1'
          tg_dir: '.'
          tg_command: '--version'

      - run: terragrunt
