name: Pr

on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - labeled

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}

      - name: test
        run: |
          sha=$(git rev-parse --short HEAD)
          echo "sha: $sha"
          git show -s --format='%an' $sha
          git show -s --format='%ae' $sha
          echo "${{ toJSON(github) }}"
