name: Print All Variables

on:
  workflow_dispatch:
  push:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print variables
        run: |
          echo '${{ toJSON(github) }}'
          echo "Author Name: $(git show -s --format='%an' ${{ github.sha }})"
          echo "Author Email: $(git show -s --format='%ae' ${{ github.sha }})"
          echo "Subject And Body: $(git show -s --format='%B' ${{ github.sha }})"
          echo EXAMPLE_ENV=aaaa >> $GITHUB_ENV

      - name: Print envs
        run: |
          env
        env:
          TEST_ENV: ${{ env.EXAMPLE_ENV ))
