name: Print All Variables

on:
  workflow_dispatch:
  push:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print variables
        run: |
          echo '${{ toJSON(github) }}'

          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            author_name="$(git show -s --format='%an' ${{ github.sha }})"
            author_email="$(git show -s --format='%ae' ${{ github.sha }})"
            echo "GIT_AUTHOR_USERNAME=${{ github.actor }}" >> $GITHUB_ENV
            echo "GIT_AUTHOR=${author_name} <${author_email}>" >> $GITHUB_ENV
            echo 'GIT_MESSAGE<<EOF' >> $GITHUB_ENV
            git show -s --format='%B' ${{ github.sha }} >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV
          else
            echo "GIT_AUTHOR_USERNAME=${{ github.event.head_commit.author.username }}" >> $GITHUB_ENV
            echo "GIT_AUTHOR=${{ github.event.head_commit.author.name }} <${{ github.event.head_commit.author.email }}>" >> $GITHUB_ENV
            echo 'GIT_MESSAGE<<EOF' >> $GITHUB_ENV
            echo -e "${{ github.event.head_commit.message }}" >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV
          fi

      - name: Print envs
        run: |
          env
          echo -e "${{ env.GIT_MESSAGE }}\n\n@${{ env.GIT_AUTHOR_USERNAME }} (${{ env.GIT_AUTHOR }})" 
        env:
          GIT_AUTHOR_USERNAME: ${{ env.GIT_AUTHOR_USERNNAME }}
          GIT_AUTHOR: ${{ env.GIT_AUTHOR }}
          GIT_MESSAGE: ${{ env.GIT_MESSAGE }}
