name: Print All Variables


on:
  workflow_dispatch:
  push:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print variables
        run: |
          echo '${{ toJSON(github) }}'
          function safe_show_commit_message() { 
            git show -s --format='%B' ${{ github.sha }} | 
            sed "s/'/'\"'\"'/g; s/\`/\```/g"
          }
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "GIT_AUTHOR_USERNAME=${{ github.actor }}" >> $GITHUB_ENV
            echo "GIT_AUTHOR=$(git show -s --format='%an' ${{ github.sha }}) <$(git show -s --format='%ae' ${{ github.sha }})>" >> $GITHUB_ENV
            echo 'GIT_MESSAGE<<EOF' >> $GITHUB_ENV
            safe_show_commit_message >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV
          else
            echo "GIT_AUTHOR_USERNAME=${{ github.event.head_commit.author.username }}" >> $GITHUB_ENV
            echo "GIT_AUTHOR=${{ github.event.head_commit.author.name }} <${{ github.event.head_commit.author.email }}>" >> $GITHUB_ENV
            echo 'GIT_MESSAGE<<EOF' >> $GITHUB_ENV
            safe_show_commit_message >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV
          fi

      - name: Print envs
        run: |
          env
          echo -e '${{ github.sha }} >> ${{ env.GIT_MESSAGE }}\n\n@${{ env.GIT_AUTHOR_USERNAME }} (${{ env.GIT_AUTHOR }})'
        env:
          GIT_AUTHOR_USERNAME: ${{ env.GIT_AUTHOR_USERNAME }}
          GIT_AUTHOR: ${{ env.GIT_AUTHOR }}
          GIT_MESSAGE: ${{ env.GIT_MESSAGE }}
