name: deploy-backend-service

on:
  push:
    branches:
      - main
    tags:
      - '**'
    paths:
      - 'projects/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ROOT: backend-service
  SLOT_NAME: staging

jobs:
  build-and-deploy:
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.environment }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ startsWith(github.ref, 'refs/tags/')
          && fromJSON(format('["{0}"]', split(github.ref_name, '/')[0]))
          || fromJSON(["dev"]) }}
    environment: ${{ matrix.environment }}
    steps:
      - run: echo ${{ matrix.environment }}
